/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

namespace BinaryData
{

//================== PushStartup.png ==================
static const unsigned char temp_binary_data_0[] =
"\x89PNG\r\n"
"\x1a\n"
"\0\0\0\rIHDR\0\0\x03\xc0\0\0\0\xa0\x08\x03\0\0\0\xf4\x14\xf5n\0\0\0\tpHYs\0\0\x0b\x13\0\0\x0b\x13\x01\0\x9a\x9c\x18\0\0""8*iTXtXML:com.adobe.xmp\0\0\0\0\0<?xpacket begin=\"\xef\xbb\xbf\" id=\"W5M0MpCehiHzreSzNTczkc9d\"?>\n"
"<x:xmpmeta xmlns:x=\"adobe:ns:meta/\" x:xmptk=\"Adobe XMP Core 5.6-c111 79.158325, 2015/09/10-01:10:20        \">\n"
"   <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n"
"      <rdf:Description rdf:about=\"\"\n"
"            xmlns:xmp=\"http://ns.adobe.com/xap/1.0/\"\n"
"            xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
"            xmlns:photoshop=\"http://ns.adobe.com/photoshop/1.0/\"\n"
"            xmlns:xmpMM=\"http://ns.adobe.com/xap/1.0/mm/\"\n"
"            xmlns:stEvt=\"http://ns.adobe.com/xap/1.0/sType/ResourceEvent#\"\n"
"            xmlns:tiff=\"http://ns.adobe.com/tiff/1.0/\"\n"
"            xmlns:exif=\"http://ns.adobe.com/exif/1.0/\">\n"
"         <xmp:CreatorTool>Adobe Photoshop CC 2015 (Macintosh)</xmp:CreatorTool>\n"
"         <xmp:CreateDate>2016-03-23T09:23:57+01:00</xmp:CreateDate>\n"
"         <xmp:ModifyDate>2016-03-23T10:27:20+01:00</xmp:ModifyDate>\n"
"         <xmp:MetadataDate>2016-03-23T10:27:20+01:00</xmp:MetadataDate>\n"
"         <dc:format>image/png</dc:format>\n"
"         <photoshop:ColorMode>2</photoshop:ColorMode>\n"
"         <xmpMM:InstanceID>xmp.iid:9a3588b9-fc5b-4ecd-b9b5-f168e448c8ce</xmpMM:InstanceID>\n"
"         <xmpMM:DocumentID>xmp.did:9a3588b9-fc5b-4ecd-b9b5-f168e448c8ce</xmpMM:DocumentID>\n"
"         <xmpMM:OriginalDocumentID>xmp.did:9a3588b9-fc5b-4ecd-b9b5-f168e448c8ce</xmpMM:OriginalDocumentID>\n"
"         <xmpMM:History>\n"
"            <rdf:Seq>\n"
"               <rdf:li rdf:parseType=\"Resource\">\n"
"                  <stEvt:action>created</stEvt:action>\n"
"                  <stEvt:instanceID>xmp.iid:9a3588b9-fc5b-4ecd-b9b5-f168e448c8ce</stEvt:instanceID>\n"
"                  <stEvt:when>2016-03-23T09:23:57+01:00</stEvt:when>\n"
"                  <stEvt:softwareAgent>Adobe Photoshop CC 2015 (Macintosh)</stEvt:softwareAgent>\n"
"               </rdf:li>\n"
"            </rdf:Seq>\n"
"         </xmpMM:History>\n"
"         <tiff:Orientation>1</tiff:Orientation>\n"
"         <tiff:XResolution>720000/10000</tiff:XResolution>\n"
"         <tiff:YResolution>720000/10000</tiff:YResolution>\n"
"         <tiff:ResolutionUnit>2</tiff:ResolutionUnit>\n"
"         <exif:ColorSpace>65535</exif:ColorSpace>\n"
"         <exif:PixelXDimension>960</exif:PixelXDimension>\n"
"         <exif:PixelYDimension>160</exif:PixelYDimension>\n"
"      </rdf:Description>\n"
"   </rdf:RDF>\n"
"</x:xmpmeta>\n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                                                                                                    \n"
"                            \n"
"<?xpacket end=\"w\"?>\x94\xb3Y\xd0\0\0\0 cHRM\0\0z%\0\0\x80\x83\0\0\xf9\xff\0\0\x80\xe9\0\0u0\0\0\xea`\0\0:\x98\0\0\x17o\x92_\xc5""F\0\0\x03\0PLTE\0\0\0\xff\xff\xff\xef\xef\xef\xdf\xdf\xdf\xcf\xcf\xcf\xbf\xbf\xbf\xaf\xaf\xaf\x9f\x9f\x9f\x8f\x8f\x8f\x80"
"\x80\x80\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd4\x83\x03"
"\xfc\0\0\0\x0btRNS\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\0JO\x01\xf2\0\0\x03\x1dIDATx\xda\xec\xdc\xdbr\xa2@\x14@\xd1\x1c\xa0\x81>\xff\xff\xc1\xf3\xe0\x05T\xe2%:\x02Uk=)\x86\xb6JjGll\x7f\x12\xd8\xad\x1f/\x01\x08\x18\x10""0 `\x10""0 `@\xc0\x80\x80""A"
"\xc0\x80\x80\x01\x01\x83\x80\x01\x01\x03\x02\x06\x04\x0c\x02\x06\x04\x0c\x08\x18\x10""0\x08\x18\x10""0 `\x10""0 `@\xc0\x80\x80""A\xc0\x80\x80\x01\x01\x03\x02\x06\x01\x03\x02\x06\x04\x0c\x02\x06\x04\x0c\x08\x18\x10""0\x08\x18\x10""0 `\x10""0 `@\xc0\x80"
"\x80""A\xc0\x80\x80\x01\x01\x03\x02\x06\x01\x03\x02\x06\x04\x0c\x02\x06\x04\x0c\x08\x18\x10""0\x08\x18\x10""0 `\xbe,\"\"\xbc\x0c\x02\xe6\xe9R\x9e\xb8u\x9f\x80\x05\x8c\x80\x05,`6\x10\xf0\xf4@S\x04,`v\x1bpD4U\xc0\x02""f\xb7\x01G\x14\x01\x0b\x98\xd5\x02"
"\xfe\xe3\xc8""3\xbd\x80\x05\xcc\xce\x02.\xa5\x94\xe6\x0f\x93\\\x02\x16""0\x1b\x08\xf8p\xb3\x8f\x88\x88V\xc0\x02""f\x8f\x01\xe7\xf0\xea@\x02\x16""0\xdb\t8\xdb\x88\x88*`\x01\xb3N\xc0\x7f\x9c\x85>\xdd\xa9/ND\x0bX\xc0l(\xe0\x14\xb0\x80\x11""0\x02""f\x85\x80"
"\x87\x88\x88\xe1z\xeb\xc5<W3\xbfX|~\xa4\xd6\xea \t\x98\x95\x03>\xdf\xf9-\xe0\xe6r\x94\xc3\xcd\xf1\xb8mp\x9c\x04\xcc[\x01\xbf""3\xf2)\xcf;\x01""7W\xff\x07\"\"\xa2\x9b\xbeJ\xed@\t\x98\xb5\x02\xeeg\xef\xa3\xcb\x01\xf7\xb3""7\xf2v\xe9\r\xbfs\xa4\x04\xcc\xf7"
"\x03\x9e/Hztb=\xe6p\x9e\xe9\xfa\xaf\x8b\x8d\x11\xb0\x80_\r\xb8y\xf4\xc9x\xc8\xccl.w\xae\x99Y^_\n"
"\x81\x80\x05\xfc\xd9\x80\xdb|\x14pw\xbbsNg\xe0>\x05\x0b\x98""7\x02~o=p[\xf3""a\xc0\xb3?:n\x18\x96\xf6""A\xc0|-\xe0RJ\xa9\xcb\xcf""7\xbf\xd3\xc6\xd5z\xa5_/\x17#`\xbe\x17\xf0\x9d\xe7[\x1c\xbe\x15\xb0\x80\xd9_\xc0\xd3\x85\xe0\"`\x01\xb3\xbb\x80\xb3""6\xf3"
"\x82\x05,`>\x19\xf0;#?\x15\xf0\x94\xb0\x80\x05\xcc\x0e\x03>\xfdpG/`\x01\xb3\x97\x80/.\xf0\xf6\xa7sh\x01\x0b\x98-\x06\xdc\xcc~[\xa7\x9f&\xad\x86\xc3_V\x01\x0b\x98-\x07\xdc_\xaf\x19\x1c\x8f\xa7\xce%\xf3\xf8\xb5I\xa7\xd0\x02\xe6\xd3\x01\x7fj\x16\xfa""8P"
"Wk\x17\xd7_\xc4\xaa\xc5$\x96\x80\xd9v\xc0\xe5r\xa7""1\xf3""4yu\xb3\x9cP\xc0\x02""fk\x01g\xb7\xb0\xce\xb7\x8d\xa5\x05\xfd\x02\x16""0\x9b\x0bx\xbez\x7f\xbc\xa9\xfa\xee\xaa""C\x04\xcc\xea\x01g\x0emDD7\xce""6\x1d>\x12\x9f\x17$\tX\xc0\x80\x80\x01\x01\x83\x80"
"\x01\x01\x03\x02\x06\x01\x03\x02\x06\x04\x0c\x08\x18\x04\x0c\x08\x18\x10""0 `\x10""0 `@\xc0 `@\xc0\x80\x80\x01\x01\x83\x80\x01\x01\x03\x02\x06\x04\x0c\x02\x06\x04\x0c\x08\x18\x04\x0c\x08\x18\x10""0 `\x10""0 `@\xc0 `@\xc0\x80\x80\x01\x01\x83\x80\x01\x01"
"\x03\x02\x06\x04\x0c\x02\x06\x04\x0c\x08\x18\x04\x0c\x08\x18\x10""0 `\x10""0 `@\xc0\x80\x80""A\xc0\x80\x80\x01\x01\x83\x80\x01\x01\x03\x02\x06\x04\x0c\x02\x06\x04\x0c\x08\x18\x04\x0c\x08\x18\xf8\xbe\x7f\0\0\0\xff\xff\x03\0\xba\xf5\x1b\xed\xe7/i@\0\0\0"
"\0IEND\xae""B`\x82";

const char* PushStartup_png = (const char*) temp_binary_data_0;


const char* getNamedResource (const char*, int&) throw();
const char* getNamedResource (const char* resourceNameUTF8, int& numBytes) throw()
{
    unsigned int hash = 0;
    if (resourceNameUTF8 != 0)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0xc1e7b9cd:  numBytes = 16112; return PushStartup_png;
        default: break;
    }

    numBytes = 0;
    return 0;
}

const char* namedResourceList[] =
{
    "PushStartup_png"
};

}
